name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://demo.backstage.io/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
          configPath: ./.lighthouserc.js
