name: Lighthouse CI
on:
  workflow_run:
    workflows: [Preview (deploy)]
    types:
      - completed
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://app.uffizzi.com/github.com/usainbloot/${{ github.event.pull_request.number }}/pull/15414/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
          configPath: ./.lighthouserc.js
